### ISSUE TITLE
BE | User registration issue

### ISSUE THREAD

**Issue by m-lukic** [vegaitglobal/posao-sansi-website#113]
![image](https://github.com/vegaitglobal/posao-sansi-website/assets/96305074/d41c5545-ca98-4385-8b51-014b620862b9)

Trenutna logika prvo proverava da li je data validan gde uvek vraca false jer je user required.

Tek nakon validacije kreiramo user-a koji bi trebao da se doda Accountu.

Endpoint ce uvek vracati BAD REQUEST

**Comment by roknicmilos** [comment]
@m-lukic, logika na BE je da se User prvo kreira pa da se onda kreira akaunt za tog user-a.
Svakako se ni jedno od ta dva nece desiti ako serializer baci validation error.
Trebalo da imas u swagger-u primer kako izgleda endpoint za registraciju (oba) i kako request treba da izgleda, tj. sta BE ocekuje u body-ju requesta.
